extends: airbnb-base
ecmaFeatures:
  jsx: true
env:
  es6: true
  browser: true
  node: true
  jest: true
rules:
  semi: 0
  no-new-func: 0
  no-console: 0
  global-require: 0
  import/no-dynamic-require: 0
  no-param-reassign:
    - 2
    - props: false