notifications:
  email: false

cache:
  directories:
    - node_modules

language: node_js

node_js:
  - "6"
  - "8"
  - "9"

script:
  - yarn test

after_success:
  - yarn contributors:generate && ./.deploy/readme.sh